server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /enclave
#  ssl:
#    enabled: true
#    key-store: classpath:keystore.p12
#    key-store-password: enclave
#    key-store-type: PKCS12
#    key-alias: myalias

spring:
  profiles:
    active: ${SPRING_PROFILE:prod}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
file:
  upload-dir: D:\enclave_project\enclave_welcome_project\springboot-project\enclave-welcome-spring-boot-service\uploads
jwt:
  signerKey: "MySuperSecretKeyThatIsLongEnough123!"
  access-duration: 3600000
  refresh-duration: 604800000

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1