server:
  port: 8080
  address: 0.0.0.0
  servlet:
    context-path: /enclave
  ssl:
    enabled: false
    key-store: classpath:keystore.p12
    key-store-password: enclave
    key-store-type: PKCS12
    key-alias: myalias

spring:

  profiles:
    active: ${SPRING_PROFILE:dev}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
file:
  upload-dir: D:\enclave_project\enclave_welcome_project\springboot-project\enclave-welcome-spring-boot-service\uploads
jwt:
  signerKey: "MySuperSecretKeyThatIsLongEnough123!"
  access-duration: 3600000
  refresh-duration: 604800000

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

springdoc:
  swagger-ui:
    defaultModelsExpandDepth: -1

openweathermap:
  api:
    key: ea44332d38d86b1345a16a3b277b7a04