server:
  port: 8080
  servlet:
    context-path: /enclave

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Enclave_db
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:
  service:
    python: http://localhost:5000/api

