server:
  port: 8080
  servlet:
    context-path: /enclave
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: enclave
    key-store-type: PKCS12
    key-alias: myalias

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/EnclaveWelcome}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:root}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:
  service:
    python: ${APP_SERVICE_PYTHON:http://localhost:5000/api}


jwt:
  signerKey: ${JWT_SIGNER_KEY}
  access-duration: 3600
  refresh-duration: 86400

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://localhost:5173}
