server:
  port: 8080
  servlet:
    context-path: /face-detection


face-detection:
  python-api-url: http://localhost:5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enclave_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
