spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

app:
  service:
    python: ${APP_SERVICE_PYTHON:http://python-service:5000/api}

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://welcome-enclave.local.hue-dev.top}
file:
  upload-dir: /app/uploads
openweathermap:
  api:
    key: ${OPENWEATHERMAP_API_KEY}