server:
  port: 8080
  servlet:
    context-path: /enclave

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/EnclaveWelcome
    username: root
    password: root
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

app:
  service:
    python: http://localhost:5000/api


jwt:
  signerKey: ${JWT_SIGNER_KEY}
  access-duration: 3600
  refresh-duration: 86400
